---
id: nag
name: Nag
full: Task list application
description: >-
  Nag is a web-based application built upon the Horde Application Framework
  which provides a simple, clean interface for managing online task lists (i.e.,
  todo lists). It also includes strong integration with the other Horde
  applications and allows users to share task lists or enable light-weight
  project management.
list:
type: application
homepage: https://www.horde.org/apps/nag
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 5.0.0
  api: 5.0.0
state:
  release: beta
  api: beta
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/content: ^2.0.5
      pear.horde.org/horde: ^5
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Controller: ^2
      pear.horde.org/Horde_Core: ^2.31
      pear.horde.org/Horde_Data: ^2
      pear.horde.org/Horde_Date: ^2.1
      pear.horde.org/Horde_Date_Parser: ^2
      pear.horde.org/Horde_Dav: ^1
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Form: ^2
      pear.horde.org/Horde_Group: ^2
      pear.horde.org/Horde_History: ^2.1
      pear.horde.org/Horde_Icalendar: ^2
      pear.horde.org/Horde_Mail: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Prefs: ^2
      pear.horde.org/Horde_Routes: ^2
      pear.horde.org/Horde_Share: ^2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Text_Filter: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_View: ^2
    ext:
      gettext: '*'
  optional:
    pear:
      pear.horde.org/Horde_ActiveSync: ^2.4
      pear.horde.org/Horde_Backup: ^1
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_OpenXchange: ^1
      pear.horde.org/Horde_Test: ^2
