<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/nag/routes.local.php and run composer horde:reconfigure

namespace Horde\Nag;

use Horde\Core\Middleware\DefaultStack;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Horde\Nag\Controller\CompleteTaskController;
use Horde\Nag\Controller\SaveTaskController;
use Horde\Nag\Controller\TaskFormController;

$mapper->buildRoute(uri: '/t/task', name: 'TaskForm')
    ->withController(TaskFormController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/task.php')
    ->add();

$mapper->buildRoute(uri: '/t/complete', name: 'CompleteTask')
    ->withController(CompleteTaskController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/task/complete.php')
    ->add();

$mapper->buildRoute(uri: '/t/save', name: 'SaveTask')
    ->withController(SaveTaskController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/task/save.php')
    ->add();

// Responsive UI Routes - PSR-style builder pattern

// Tasks List - Primary route with legacy smartmobile secondary
$mapper->buildRoute(uri: '/responsive', name: 'ResponsiveTasks')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/smartmobile')
    ->withSecondaryRoute('/smartmobile.php')
    ->add();

// Filter: All Tasks
$mapper->buildRoute(uri: '/responsive/all', name: 'ResponsiveTasksAll')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Filter: Incomplete Tasks
$mapper->buildRoute(uri: '/responsive/incomplete', name: 'ResponsiveTasksIncomplete')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Filter: Complete Tasks
$mapper->buildRoute(uri: '/responsive/complete', name: 'ResponsiveTasksComplete')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Filter: Future Tasks
$mapper->buildRoute(uri: '/responsive/future', name: 'ResponsiveTasksFuture')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Filter: Future Incomplete Tasks
$mapper->buildRoute(uri: '/responsive/future-incomplete', name: 'ResponsiveTasksFutureIncomplete')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Add New Task
$mapper->buildRoute(uri: '/responsive/add', name: 'ResponsiveTaskAdd')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Task Detail View
$mapper->buildRoute(uri: '/responsive/task/:tasklist/:id', name: 'ResponsiveTask')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->requires('tasklist', '[a-zA-Z0-9\-_]+')
    ->requires('id', '[a-zA-Z0-9\-_]+')
    ->withMiddleware(DefaultStack::get())
    ->add();

// Task Edit View
$mapper->buildRoute(uri: '/responsive/edit/:tasklist/:id', name: 'ResponsiveTaskEdit')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->requires('tasklist', '[a-zA-Z0-9\-_]+')
    ->requires('id', '[a-zA-Z0-9\-_]+')
    ->withMiddleware(DefaultStack::get())
    ->add();
